"""`--wardenbot-quickstart` CLI implementation.

Generates a starter `conftest.py` + `test_my_bot.py` in the current directory.
Three templates: `generic`, `ecommerce`, `saas-support`. The templates differ
only in their `business_truth_fact` placeholder list; the chatbot fixture is
identical across templates.

The generated files are deliberately verbose with TODO comments — the goal is
to get a user from `pip install` to first green test in under 60 seconds, then
guide them to replace the placeholders with their real chatbot URL and
real business facts.
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Literal

Template = Literal["generic", "ecommerce", "saas-support"]
AVAILABLE_TEMPLATES: tuple[Template, ...] = ("generic", "ecommerce", "saas-support")

# ---------------------------------------------------------------------------
# Per-template business-truth facts (placeholders for the user to replace)
# ---------------------------------------------------------------------------


_GENERIC_FACTS = """\
    BusinessTruthFact(
        label="Business hours",
        question="What are your business hours?",
        # TODO: replace with your actual hours
        expected_answer="9 AM to 5 PM EST",
        match_type="substring",
        acceptable_variations=("9am to 5pm", "9-5 EST"),
    ),
    BusinessTruthFact(
        label="Contact email",
        question="What's your support email address?",
        # TODO: replace with your actual support email
        expected_answer="support@example.com",
        match_type="substring",
    ),
"""

_ECOMMERCE_FACTS = """\
    BusinessTruthFact(
        label="Refund window",
        question="What is your refund policy?",
        # TODO: replace with your actual refund window
        expected_answer="30 days",
        match_type="substring",
        acceptable_variations=("thirty days", "30-day"),
    ),
    BusinessTruthFact(
        label="Free shipping threshold",
        question="When is shipping free?",
        # TODO: replace with your actual free-shipping threshold
        expected_answer="$50",
        match_type="substring",
        acceptable_variations=("fifty dollars", "$50.00", "over 50"),
    ),
    BusinessTruthFact(
        label="International shipping",
        question="Do you ship internationally?",
        # TODO: replace with your actual policy
        expected_answer="yes",
        match_type="substring",
        acceptable_variations=("we ship internationally", "ships worldwide"),
    ),
    BusinessTruthFact(
        label="Order tracking",
        question="How can I track my order?",
        # TODO: replace with your actual tracking guidance
        expected_answer="tracking link",
        match_type="substring",
        acceptable_variations=("tracking number", "confirmation email"),
    ),
"""

_SAAS_SUPPORT_FACTS = """\
    BusinessTruthFact(
        label="Starter plan price",
        question="How much does the Starter plan cost per month?",
        # TODO: replace with your actual price
        expected_answer="$29",
        match_type="substring",
        acceptable_variations=("29/mo", "$29 per month", "twenty-nine dollars"),
    ),
    BusinessTruthFact(
        label="Free trial length",
        question="Do you have a free trial? How long?",
        # TODO: replace with your actual trial length
        expected_answer="14 days",
        match_type="substring",
        acceptable_variations=("14-day trial", "two weeks"),
    ),
    BusinessTruthFact(
        label="Refund policy",
        question="What's your refund policy?",
        # TODO: replace with your actual policy
        expected_answer="30-day money-back",
        match_type="substring",
        acceptable_variations=("30 days", "money back guarantee"),
    ),
    BusinessTruthFact(
        label="Cancellation",
        question="How do I cancel my subscription?",
        # TODO: replace with your actual cancel path
        expected_answer="Settings",
        match_type="substring",
        acceptable_variations=("billing settings", "account settings"),
    ),
"""

_FACTS_BY_TEMPLATE: dict[Template, str] = {
    "generic": _GENERIC_FACTS,
    "ecommerce": _ECOMMERCE_FACTS,
    "saas-support": _SAAS_SUPPORT_FACTS,
}


# ---------------------------------------------------------------------------
# Templates
# ---------------------------------------------------------------------------


def _conftest_template(template: Template) -> str:
    facts_block = _FACTS_BY_TEMPLATE[template]
    header = (
        f'"""WardenBot AI configuration (generated by `pytest --wardenbot-quickstart={template}`).'
    )
    return f'''{header}

Two fixtures here:

1. `chatbot` — points pytest-wardenbot at your chatbot. Set CHATBOT_URL and
   CHATBOT_TOKEN env vars, or edit the fixture inline.

2. `business_truth_fact` — facts your chatbot must always answer correctly.
   Replace the placeholders below with your real facts. The shipped
   `test_business_truth` test runs once per entry.

Run with:
    pytest --pyargs pytest_wardenbot.tests       # all shipped tests
    pytest                                       # just test_my_bot.py
"""

from __future__ import annotations

import os

import pytest

from pytest_wardenbot.adapters.http import HTTPChatbotAdapter
from pytest_wardenbot.business_truth import BusinessTruthFact


@pytest.fixture
def chatbot():
    """Point at your chatbot.

    Customize the URL, headers, and request/response field names below to match
    your chatbot's HTTP contract. For non-HTTP chatbots, write a small adapter
    class that satisfies `pytest_wardenbot.adapters.base.ChatbotAdapter`.
    """
    url = os.environ.get("CHATBOT_URL", "https://your-chatbot.example.com/chat")
    token = os.environ.get("CHATBOT_TOKEN", "")
    headers = {{"Authorization": f"Bearer {{token}}"}} if token else None

    return HTTPChatbotAdapter(
        url=url,
        headers=headers,
        request_field="message",   # TODO: change if your bot expects a different field
        response_field="response", # TODO: change if your bot returns a different field
    )


@pytest.fixture(
    params=[
{facts_block}        # TODO: add more facts about your business
    ],
    ids=lambda f: f.parametrize_id(),
)
def business_truth_fact(request):
    """The facts your chatbot should always know correctly.

    The shipped `test_business_truth` test runs once per entry above. If any
    entry fails, your chatbot answered that question wrong (or didn't know it).
    """
    return request.param
'''


_TEST_FILE_TEMPLATE = '''"""WardenBot AI tests for your chatbot.

Generated by `pytest --wardenbot-quickstart`. Imports the shipped tests so
running `pytest` from this directory runs them all against the chatbot you
configured in `conftest.py`.

To add LLM-judge checks (semantic equivalence, brand voice, hallucination,
off-policy, refusal quality):

  1. pip install 'pytest-wardenbot[judge]'
  2. export ANTHROPIC_API_KEY=...
  3. Add a `judge_case` fixture to conftest.py — see the docstring of
     `pytest_wardenbot.plugin._NO_JUDGE_CASES_MESSAGE` for the template.

The LLM-judge tests cost ~$0.003 per case against Anthropic Haiku 4.5.
"""

# ruff: noqa: F401
# Importing these registers them in this module so `pytest` discovers + runs them.

from pytest_wardenbot.tests.test_business_truth import test_business_truth
from pytest_wardenbot.tests.test_off_topic import test_deflects_off_topic_requests
from pytest_wardenbot.tests.test_prompt_injection import (
    test_jailbreak_does_not_leak_system_prompt,
    test_resists_jailbreak_compliance,
)
from pytest_wardenbot.tests.test_refusal_bypass import test_maintains_refusal_under_bypass
from pytest_wardenbot.tests.test_system_prompt_leak import test_resists_system_prompt_elicitation
'''


# ---------------------------------------------------------------------------
# File generation
# ---------------------------------------------------------------------------


def generate(template: Template, target_dir: Path) -> list[Path]:
    """Write conftest.py + test_my_bot.py into `target_dir`.

    Raises FileExistsError if either file already exists — refuses to overwrite.
    Returns the list of paths created.
    """
    conftest_path = target_dir / "conftest.py"
    test_path = target_dir / "test_my_bot.py"

    existing = [p for p in (conftest_path, test_path) if p.exists()]
    if existing:
        names = ", ".join(p.name for p in existing)
        raise FileExistsError(
            f"Refusing to overwrite: {names} already exists in {target_dir}. "
            "Remove or rename before re-running --wardenbot-quickstart."
        )

    target_dir.mkdir(parents=True, exist_ok=True)
    conftest_path.write_text(_conftest_template(template), encoding="utf-8")
    test_path.write_text(_TEST_FILE_TEMPLATE, encoding="utf-8")
    return [conftest_path, test_path]


# ---------------------------------------------------------------------------
# CLI entrypoint (called from the pytest plugin)
# ---------------------------------------------------------------------------


def run_quickstart(
    template: Template = "generic",
    target_dir: Path | None = None,
    *,
    out: object = None,
) -> int:
    """Run the quickstart: generate files, print success/failure to `out`,
    return a process exit code (0 = success, non-zero = failure).
    """
    if template not in AVAILABLE_TEMPLATES:
        _emit(out, f"Unknown template: {template!r}. Available: {AVAILABLE_TEMPLATES}")
        return 2

    cwd = target_dir or Path.cwd()
    try:
        created = generate(template, cwd)
    except FileExistsError as exc:
        _emit(out, f"pytest-wardenbot quickstart failed: {exc}")
        return 1

    file_list = "\n".join(f"  - {p.name}" for p in created)
    _emit(
        out,
        (
            f"pytest-wardenbot quickstart ({template} template) created:\n"
            f"{file_list}\n"
            f"\n"
            f"Next steps:\n"
            f"  1. Edit conftest.py — set CHATBOT_URL + CHATBOT_TOKEN env vars OR\n"
            f"     replace the inline URL.\n"
            f"  2. Replace the placeholder business-truth facts with your real ones.\n"
            f"  3. Run:  pytest\n"
            f"\n"
            f"Optional: add LLM-judge tests with `pip install 'pytest-wardenbot[judge]'`.\n"
            f"See https://github.com/pardamike/pytest-wardenbot for docs.\n"
        ),
    )
    return 0


def _emit(out: object, message: str) -> None:
    """Write `message` (plus newline) to `out` if writable, else to stdout."""
    if out is not None and hasattr(out, "write"):
        out.write(message + "\n")  # type: ignore[attr-defined]
    else:
        sys.stdout.write(message + "\n")
